services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php82-prof
    depends_on:
      - db
    image: php:8.2-apache
    volumes:
      - ./lacosina:/var/www/html/
    ports:
      - 80:80
  db:
    container_name: mysql8-prof
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: MySecurePwd
      MYSQL_DATABASE: lacosina
      MYSQL_USER: myuser
      MYSQL_PASSWORD: monpassword
    ports:
      - 3306:3306
  phpmya:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-prof
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: myuser
      PMA_PASSWORD: monpassword
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80